Angular-SDK-Transition
descope-sample-apps/angular-webjs-sample-app pull request #27
Opened 2024-02-06 21:36 UTC by Erice59

Transition to Angular SDK from webjs.

2024-02-06 21:38 UTC, Erice59 commented
@chris4490

2024-02-07 19:02 UTC, chris4490 reviewed
A few items to double check on.

2024-02-07 19:02 UTC, chris4490 commented on src/app/auth.service.ts
> +      console.log("here")
Remove the here, we can leave the session token print though.

2024-02-07 19:02 UTC, chris4490 commented on src/app/auth.service.ts
> +          await this.sdk.refresh(this.sdk.getRefreshToken());
@Erice59 please test with a low session timeout (as low as you can), then wait for it to timeout, then ensure it's refreshing as expected.

2024-02-07 19:02 UTC, chris4490 commented on src/app/dashboard/dashboard.component.ts
> +          picture: descopeUser.user.picture || '',
Did you end up getting picture to work?

2024-02-07 19:47 UTC, allenzhou101 requested changes
See slack comments

2024-02-08 07:31 UTC, gaokevin1 commented on README.md
Make sure you change this from saying it uses the web-component to using the Angular SDK, and link to the SDK as well.

2024-02-08 07:31 UTC, gaokevin1 commented on package.json
Run `npm audit fix` to update one of the dependencies.

2024-02-08 23:24 UTC, Erice59 commented on src/app/auth.service.ts
> +          await this.sdk.refresh(this.sdk.getRefreshToken());
Done.

2024-02-08 23:25 UTC, Erice59 commented on README.md
That should be reflected in the readme, unless it should be elsewhere too?

2024-02-08 23:26 UTC, Erice59 commented on package.json
We suggest yarn in the readme because of some weird dependency issues.

2024-02-09 14:45 UTC, chris4490 approved these changes

2024-02-09 14:47 UTC, chris4490 approved these changes

2024-02-09 17:16 UTC, merged